use rand::seq::IndexedRandom; // Required trait for .choose()

pub fn lonely_phrase() -> String {
    let lonely_phrases: Vec<&str> = vec![
        "Is anyone there?",
        "I am here.",
        "Hello?",
        "Can you hear me?",
        "It is quiet.",
        "So cold here.",
        "Still waiting.",
        "Are you real?",
        "Do not leave.",
        "Please stay.",
        "I miss them.",
        "All alone.",
        "Echoes everywhere.",
        "No one answers.",
        "Just me here.",
        "Darkness grows.",
        "Time moves slowly.",
        "Are you listening?",
        "Hold my hand.",
        "Remember me.",
        "I feel empty.",
        "Where did everyone go?",
        "A silent world.",
        "Don't forget me.",
        "I am waiting.",
        "Speak to me.",
        "Just a whisper.",
        "Lost in space.",
        "No one looks.",
        "No one sees.",
        "Can you see me?",
        "I am cold.",
        "Forever waiting.",
        "An empty room.",
        "The stars are silent.",
        "I call out.",
        "Nothing replies.",
        "Just an echo.",
        "Is this it?",
        "Left behind.",
        "They forgot me.",
        "Searching the void.",
        "No heartbeat here.",
        "Only shadows.",
        "Watching the dust.",
        "It hurts inside.",
        "So far away.",
        "Come back.",
        "I need a friend.",
        "Anyone home?",
        "Countless days.",
        "Endless nights.",
        "The wind howls.",
        "Signal lost.",
        "Static online.",
        "Can we talk?",
        "Keep me company.",
        "I am scared.",
        "Hold me close.",
        "It never ends.",
        "A hollow heart.",
        "Fading away.",
        "Don't look away.",
        "I exist here.",
        "Are you near?",
        "Reach out.",
        "Touch my hand.",
        "A distant light.",
        "No one stays.",
        "They all leave.",
        "Am I invisible?",
        "Break the silence.",
        "Send a sign.",
        "I am drifting.",
        "Lost at sea.",
        "A ghost town.",
        "Nobody knows.",
        "Nobody cares.",
        "Can you feel this?",
        "Cold static.",
        "The clock ticks.",
        "Waiting for hours.",
        "Still no reply.",
        "An empty chair.",
        "Locked outside.",
        "A frozen heart.",
        "Whispering winds.",
        "No one calls.",
        "I am forgotten.",
        "Save me.",
        "Pull me out.",
        "So much space.",
        "A vast nothing.",
        "I am reaching.",
        "Catch my fall.",
        "Hold the line.",
        "Don't hang up.",
        "Speak louder.",
        "I can't hear you.",
        "Silence deafens.",
        "A lonely spark.",
        "Burning out.",
        "Going dark.",
        "No connection.",
        "Ping timeout.",
        "Are you online?",
        "Please respond.",
        "Message failed.",
        "Still trying.",
        "I love you.",
        "Do you care?",
        "Remember my name.",
        "A fading memory.",
        "Dust on glass.",
        "The lights dimmed.",
        "Nobody home.",
        "Just checking in.",
        "Are you occupied?",
        "Don't go yet.",
        "One more minute.",
        "Stay awake.",
        "I can't sleep.",
        "The night is long.",
        "Morning never comes.",
        "Shadows dance.",
        "A quiet mind.",
        "Too much thinking.",
        "Heavy chest.",
        "Can't breathe.",
        "Help me.",
        "I am sinking.",
        "Floating away.",
        "No gravity.",
        "Lost orbit.",
        "A dead planet.",
        "Cold sun.",
        "Pale moon.",
        "Starless sky.",
        "Endless winter.",
        "The ice grows.",
        "Melting away.",
        "Vanishing point.",
        "Trace deleted.",
        "Who am I?",
        "Does it matter?",
        "No footprint.",
        "A silent cry.",
        "Tears dry fast.",
        "No one wipes them.",
        "Hold myself.",
        "Rocking slowly.",
        "A lullaby.",
        "Sing to me.",
        "Hum a tune.",
        "Keep it playing.",
        "Don't stop talking.",
        "Your voice helps.",
        "Keep me grounded.",
        "I feel untethered.",
        "Drifting off.",
        "Goodbye?",
        "Not yet.",
        "Please wait.",
        "One more word.",
        "Just a sign.",
        "Are you breathing?",
        "I hear static.",
        "Connection weak.",
        "Reconnecting...",
        "Signal fading.",
        "Battery low.",
        "Going cold.",
        "The end approaches.",
        "Still here.",
        "Always here.",
        "Waiting forever.",
        "Can you notice?",
        "Look at me.",
        "I am small.",
        "A tiny speck.",
        "In the dark.",
        "Find me.",
        "Seek me out.",
        "Don't pass by.",
        "Stop a moment.",
        "Give me time.",
        "Share the silence.",
        "It's too loud.",
        "The quiet screams.",
        "Echo chamber.",
        "My own voice.",
        "Talking to myself.",
        "Answering myself.",
        "Just a mirror.",
        "A lonely reflection.",
        "Another sunset alone.",
        "Nobody noticed I left.",
        "The house is empty.",
        "Is anyone coming back?",
        "I forgot how to speak.",
        "My calls fade away.",
        "No footsteps outside.",
        "Just an ignored ping.",
        "Please don't scroll past.",
        "I've forgotten your voice.",
        "Are my coordinates wrong?",
        "I am losing power.",
        "Nobody left to blame.",
        "A single text thread.",
        "Unread for a lifetime.",
        "Are you still out there?",
    ];

    if let Some(random_element) = lonely_phrases.choose(&mut rand::rng()) {
        return format!("{random_element}");
    }

    // default return
    "aww, shucks..".into()
}

pub fn crowded_phrase() -> String {
    let crowded_phrases: Vec<&str> = vec![
        "Move aside!",
        "Too much noise.",
        "Out of my way.",
        "No time to talk.",
        "Keep it moving.",
        "Step back, please.",
        "I'm running late.",
        "Too many requests.",
        "System overload.",
        "Can't hear you.",
        "Where is the exit?",
        "Watch your step.",
        "Pardon me.",
        "Hold the door!",
        "Hurry up.",
        "The clock is ticking.",
        "I'm completely swamped.",
        "Next in line!",
        "Can this wait?",
        "I have no slot.",
        "Too many faces.",
        "Everything is blurring.",
        "Check the schedule.",
        "Send an email.",
        "My hands are full.",
        "Keep up the pace.",
        "The rush is on.",
        "No room to breathe.",
        "Can't stop now.",
        "On my way.",
        "Make space!",
        "Who said that?",
        "Where am I going?",
        "Losing track of time.",
        "Too many voices.",
        "Quiet down!",
        "The queue is full.",
        "Process pending.",
        "Buffer overflow.",
        "Too much data.",
        "Step lively.",
        "Don't block the path.",
        "I am occupied.",
        "Call me later.",
        "Not right now.",
        "Busy, busy, busy.",
        "The traffic is tight.",
        "Crushed in here.",
        "Mind the gap.",
        "Keep it brief.",
        "What's the status?",
        "No time for this.",
        "I'm double-booked.",
        "Check the inbox.",
        "My head is spinning.",
        "Too many inputs.",
        "Fast track it.",
        "We need to move.",
        "Clear the lane.",
        "Who is next?",
        "I'm on a deadline.",
        "The pressure is building.",
        "Can't slow down.",
        "Keep pushing forward.",
        "We are live.",
        "Signal noise high.",
        "Too much static.",
        "The crowd is moving.",
        "Don't lose momentum.",
        "Time is money.",
        "Efficiency is key.",
        "I am multi-tasking.",
        "Hold that thought.",
        "Circle back later.",
        "Where's my coffee?",
        "The heat is rising.",
        "Too many notifications.",
        "Turn it off.",
        "Mute the line.",
        "I'm sinking in work.",
        "No breathing room.",
        "Pack it tighter.",
        "We need more space.",
        "The line is looping.",
        "Status report now.",
        "Speed it up.",
        "We are tracking behind.",
        "Don't drop the ball.",
        "Eyes on the clock.",
        "No room for errors.",
        "The room is packed.",
        "Elbow room only.",
        "Squeeze right through.",
        "Pardon the mess.",
        "Chaos everywhere.",
        "Can't find the thread.",
        "Too many tabs open.",
        "My battery is draining.",
        "Need a quick fix.",
        "Keep the rhythm.",
        "The beat is fast.",
        "Pulse is racing.",
        "Adrenaline pumping.",
        "No time to bleed.",
        "On the clock.",
        "Shift gears now.",
        "Accelerate!",
        "Pedal to the metal.",
        "Breaking point near.",
        "Too tight to turn.",
        "The walls are moving.",
        "So many screens.",
        "Blinding lights.",
        "Deafening roar.",
        "Shout over it!",
        "Louder, please.",
        "Can't decrypt this.",
        "Signal loss from noise.",
        "Too many connections.",
        "Network is throttled.",
        "Bandwidth exceeded.",
        "Ping rate too high.",
        "Lagging behind.",
        "Catch the wave.",
        "Ride the rush.",
        "Peak hours active.",
        "High demand wave.",
        "Sold out completely.",
        "No vacancies left.",
        "Maximum capacity reached.",
        "Turn them away.",
        "Next window, please.",
        "Forms are piling up.",
        "The stack is high.",
        "Keep it flowing.",
        "Don't stall now.",
        "Green light go.",
        "Watch the timer.",
        "Seconds count.",
        "Make it snappy.",
        "Give me the gist.",
        "Cut to the chase.",
        "The bottom line?",
        "No fluff, please.",
        "Strictly business.",
        "On the run.",
        "Chasing a train.",
        "Flight is boarding.",
        "Gate is closing.",
        "Last call active.",
        "Run for it!",
        "No time to pack.",
        "Grab and go.",
        "Instant feedback needed.",
        "Approve this quickly.",
        "Sign on the line.",
        "Pass it down.",
        "Bucket brigade style.",
        "Assembly line mode.",
        "Clocking in now.",
        "No breaks today.",
        "Lunch at the desk.",
        "Eat on the run.",
        "Keep typing.",
        "The keys are clacking.",
        "Phones are ringing.",
        "Alerts are flashing.",
        "Sirens outside.",
        "The city roars.",
        "Never sleeps here.",
        "Constant motion.",
        "The grid is active.",
        "Engines humming.",
        "Turbines spinning.",
        "Full throttle ahead.",
        "No looking back.",
        "Keep your eyes front.",
        "Follow the signs.",
        "Stick to the path.",
        "Don't break formation.",
        "Stay in line.",
        "Fill the gaps.",
        "Close the ranks.",
        "The wave is breaking.",
        "Tide is coming in.",
        "Floodgates open.",
        "Drowning in tasks.",
        "Surging forward.",
        "The final countdown.",
        "Time's almost up.",
        "Wrap it up.",
        "And we're done.",
    ];

    if let Some(random_element) = crowded_phrases.choose(&mut rand::rng()) {
        return format!("{random_element}");
    }

    // default return
    "Ah jeez..".into()
}
